index:
    path: /
    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

forgot_password:
    path: /forgot-password
    controller: App\Controller\SecurityController:forgotPassword

reset_password:
    path: /reset-password/{token}/{id}
    controller: App\Controller\SecurityController:resetPassword
    
change_password:
    path: /user/change-password/
    controller: App\Controller\SecurityController:changePassword
    
edit_profile:
    path: /user/profile/
    controller: App\Controller\SecurityController:editProfile

user_registration:
    path: /register
    controller: App\Controller\RegistrationController::register

user_home:
    path: /user/home
    controller: App\Controller\DefaultController::user